Feature/get item by partner
unsri-hackers/ecommerce pull request #42
Opened 2021-06-09 03:22 UTC by onirutlA

Close #32

2021-06-09 21:14 UTC, lloistborn requested changes
please have a look

2021-06-09 21:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/Inventory.java
> +    public Inventory(String itemName, Double price, Integer fkSellerId, List<Photo> photos) {
kenapa dibikin banyak constructor?

2021-06-09 21:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/application/behaviours/seller/commands/GetSellerInventories.java
> +public class GetSellerInventories implements BaseCommand<List<Seller>> {
karena get bukan bagian command (perintah) tetapi hanyak query (memilih/mengambil) data, sebaiknya dimasukkan ke dalam package queries

2021-06-09 21:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/Photo.java
> +package com.unsri.ecommerce.domain.models;
sebaiknya kita tambah id untuk keperluan refer ke inventory atau seller.
jika atribut kelas ini hanya id, path dan nama, maka kita tidak tahu tabel ini merupakan tabel keperluan simpan foto inventory atau foto profile user

2021-06-09 21:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/Seller.java
> +    public Seller(Integer id, String username, String email) {
kenapa menggunakan multiple konstruktor?

2021-06-09 21:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/infrastructure/repository/SellerRepository.java
> +public interface SellerRepository extends JpaRepository<Seller, String> {
kenapa Integer diubah jadi String?

2021-06-09 21:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/presentation/controllers/InventoryController.java
> +                photos.add(new Photo("www.google.com", "google"));
apakah tujuan menambahkan dummy foto ditambahkan sebagai response?

2021-06-09 21:14 UTC, lloistborn commented on src/main/resources/data.sql
> +INSERT INTO INVENTORY (id, item_name, price) VALUES (1, 'Macbook Air', 10.30);
insert value dengan 1 disetiap baris akan mengakibatkan multiple id duplicated dan breaking proses insert kedua dan ketiga karena id merupakan PK

2021-06-09 21:14 UTC, lloistborn commented on src/test/java/com/unsri/ecommerce/application/behaviours/seller/queries/GetSellerInventoriesTests.java
> +        when(sellerRepository.findSellerByIdAndType(sellerId, sellerType, pageable)).thenReturn(sellers);
nama function test untuk inventories tapi isi dari function memanggil seller,
seharusnya isi function memanggil fungsi untuk get inventory

2021-06-10 04:35 UTC, onirutlA commented on src/main/java/com/unsri/ecommerce/presentation/controllers/InventoryController.java
> +                photos.add(new Photo("www.google.com", "google"));
hanya untuk mencontohkan response kak karena data untuk photo belum ada

2021-06-10 04:35 UTC, onirutlA commented on src/main/java/com/unsri/ecommerce/domain/models/Inventory.java
> +    public Inventory(String itemName, Double price, Integer fkSellerId, List<Photo> photos) {
jdi constructor kosong dan constructor full sudah cukup kak?

2021-06-10 04:35 UTC, onirutlA commented on src/main/java/com/unsri/ecommerce/domain/models/Seller.java
> +    public Seller(Integer id, String username, String email) {
jdi constructor kosong dan constructor full sudah cukup kak?

2021-06-10 04:35 UTC, onirutlA commented on src/main/java/com/unsri/ecommerce/infrastructure/repository/SellerRepository.java
> +public interface SellerRepository extends JpaRepository<Seller, String> {
belum diubah kak ketika ingin menyesuaikan dengan api spec tapi ternyata harus di tetapkan sebagain integer

2021-06-10 04:35 UTC, onirutlA commented on src/main/java/com/unsri/ecommerce/domain/models/Photo.java
> +package com.unsri.ecommerce.domain.models;
tambah 2 id untuk inventory dan seller?

2021-06-10 04:35 UTC, onirutlA commented on src/main/resources/data.sql
> +INSERT INTO INVENTORY (id, item_name, price) VALUES (1, 'Macbook Air', 10.30);
ok kak

2021-06-11 10:14 UTC, lloistborn approved these changes

2021-06-11 10:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/PhotoInventory.java
> +    public PhotoInventory(Integer id, String path, String name) {
remove ini karena belum dibutuhkan

2021-06-11 10:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/PhotoInventory.java
> +    }
tambahkan ToString()

2021-06-11 10:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/PhotoSeller.java
> +    public PhotoSeller(Integer id, String path, String name) {
remove parameter id karena auto generated

2021-06-11 10:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/presentation/controllers/InventoryController.java
> +            @RequestParam(value = "sellerType") int sellerType,
sellerType tidak dibutuhkan, please remove

2021-06-11 10:14 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/presentation/controllers/InventoryController.java
> +            @RequestParam(value = "sellerId") int sellerId,
sellerId didapat dari header Authorization

2021-06-11 10:15 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/Inventory.java
> +    public Inventory(String itemName, Double price, Integer fkSellerId, List<Photo> photos) {
please check lagi kalo ada contructor yang tidak terpakai

2021-06-11 10:15 UTC, lloistborn commented on src/main/java/com/unsri/ecommerce/domain/models/Seller.java
> +    public Seller(Integer id, String username, String email) {
please check lagi kalo ada contructor yang tidak terpakai

2021-06-11 12:49 UTC, merged